/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

    plugins {
    id("flutter_application_covid19.java-library-conventions")
}
